language: java
jdk:
- oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
after_success:
- mvn clean cobertura:cobertura coveralls:report
env:
  global:
    secure: dPq6gmrA6Iq750PN/Caai9YhVmMAf+w2KpHJIctb8Wz5Vt/QDNb1fdFdNmUVasHWUFNxFtNTekrbKAf9Hk6VpFnykM9XGygxJG05OUzELnPjm4qdUDOtlsXC1/mfKNK+JU1v5pywRAOgKhjZXUHqBNSNHIV4F8fZr40/W5kMkjuiwVnVcx50C6tZvDovZlMiRHyD4gteEE4euZKLJlKtZ3aVGuqXAsN3mrhkkTIiORUaVdBi6YAJ6Utr5yyIvv3RGQ0tnCZ4nOlFfDzThANbiE3nymSTew51PgoJQnOHSRthwss7r8UOi9IkDyOH0c+UNw0Yvy1vOTAUirh2vyTCGMPJgPTekV0VqYO9JmTdn3cO28jyh2O3v88JmQrRLdhCmrjnZNkf2mRPvBGLc6Acmjhc8KfhYbuuyz+hakVw5HUeUzQcQa6rTuDsZZZMoce6TDi1qKhauKlS39vnQXPQaK/mjznwbCpB0kzXfaapY+5662sEmfsz3cs2ODr+/7CJleMShJAheuTNnbqOD/6Y6QSyqBJ0eLZCl081D4tc0PTtwHiCJ/TGx5oaCGf9kGyZ0CqCtWeMACYRhDuGX+qvM8BbeL2u/tNUCjZpY6WPDowsBoLM9l91r9bWur7NFku2OLhmAOyEEQApBmkjEcTr7A0Jm6+mZIADPv7kE4M02FQ=
